# Generated by Django 3.2.7 on 2021-11-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='medic',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='api.medic'),
        ),
    ]
