# Generated by Django 3.2.7 on 2021-10-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='pesel',
            new_name='PESEL',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientmodel',
            name='gender',
        ),
    ]
