# Generated by Django 3.2.7 on 2022-01-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('token', models.TextField()),
                ('event_description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('http_method', models.CharField(max_length=20)),
            ],
        ),
    ]
