# Generated by Django 3.2.9 on 2021-12-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='work_start',
        ),
    ]
