# Generated by Django 3.2.7 on 2022-01-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMonth',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('jan', models.FloatField()),
                ('feb', models.FloatField()),
                ('mar', models.FloatField()),
                ('apr', models.FloatField()),
                ('may', models.FloatField()),
                ('jun', models.FloatField()),
                ('jul', models.FloatField()),
                ('aug', models.FloatField()),
                ('sep', models.FloatField()),
                ('oct', models.FloatField()),
                ('nov', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budgetmonth')),
            ],
        ),
    ]
