# Generated by Django 3.2.8 on 2021-11-10 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_operation_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(),
        ),
    ]
