# Generated by Django 3.2.8 on 2021-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211110_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_prepare_time', models.TimeField()),
                ('working_start_hour', models.TimeField()),
                ('working_end_hour', models.TimeField()),
                ('child_interval_hour', models.TimeField()),
                ('difficult_interval_hour', models.TimeField()),
            ],
        ),
    ]
